//roles.js

module.exports = {
  PATIENT: "PATIENT",
  DOCTOR: "DOCTOR",
  THERAPIST: "THERAPIST",
  TRANSLATOR: "TRANSLATOR",
  DONOR: "DONOR",
  NGO: "NGO",
  MISSION_COORDINATOR: "MISSION_COORDINATOR",
  VOLUNTEER: "VOLUNTEER",
  COURIER: "COURIER",
  PHARMACY: "PHARMACY",
  HOSPITAL_STAFF: "HOSPITAL_STAFF",
  CONTENT_EDITOR: "CONTENT_EDITOR",
  ALERT_MANAGER: "ALERT_MANAGER",
  FINANCE_MANAGER: "FINANCE_MANAGER",
  MODERATOR: "MODERATOR",
  AUDITOR: "AUDITOR",
  ADMIN: "ADMIN",
};
